### ISSUE TITLE
Rating - Support Custom Images, tooltips, titles, and rate values for rating options

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5149]
- [x] surveyjs/survey-library#5659
- [x] surveyjs/survey-library#5680
- [x] surveyjs/survey-library#5827
- [x] surveyjs/survey-library#5916
- [x] surveyjs/survey-library#5939
- [x] surveyjs/survey-library#5971
- [x] surveyjs/survey-creator#3963
- [x] surveyjs/survey-library#5998
- [x] #5973
- [x] https://github.com/surveyjs/service/issues/1056
- [x] https://github.com/surveyjs/survey-pdf/issues/223

<details>
<summary>Users' requests</summary>
- [ ] Support images / markdown emoji for Ranking question to implement a different kind of ranking quesions: like jQurey Bar Rating(https://surveyjs.io/form-library/examples/bar-rating-widget-javascript/reactjs) and Emotions Rating(https://surveyjs.io/form-library/examples/custom-widget-emotionsratings/reactjs). 

Related tickets:
* [T3203 - Want to Display Stars in Rating Box](https://surveyjs.answerdesk.io/internal/ticket/details/T3203)
* [Add support for images in Ranking question type](https://github.com/surveyjs/survey-library/issues/5134)
* [T3151 - Implement Smily in Likert scale](https://surveyjs.answerdesk.io/internal/ticket/details/T3151)
* [T10410 - Star Rating](https://surveyjs.answerdesk.io/internal/ticket/details/T10410)
* [T11607 - Smileys in the rating field](https://surveyjs.answerdesk.io/internal/ticket/details/T11607)
* [T11944 - Add custom properties to widget when using model prop on Survey React component](https://surveyjs.answerdesk.io/internal/ticket/details/T11944)
_images on top of the rating and extra fields that are further to the right_
![Image](https://user-images.githubusercontent.com/22372972/217466532-46bed6d0-d964-49ac-90d7-fcbb106d1c79.png)

- [ ] Support Tooltips for Ranking items.
Related tickets:
* [How add tooltip for idivdual emoji expression](https://surveyjs.answerdesk.io/internal/ticket/details/T3350)

- [ ] Title for rating options
[Add title attribute for rate item in rating question in Creator](https://surveyjs.answerdesk.io/internal/ticket/details/T4842)
</details>

**Comment by JaneSjs** [comment]
+ PDF export support
[T11710 - Pdf export issues: Exporting Custom Questions and Third-Party Widgets](https://surveyjs.answerdesk.io/internal/ticket/details/T11710)

**Comment by mikeamelin** [comment]
Design —
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=15858%3A138583

**Comment by novikov82** [comment]
1 - Terrible
2 - Very Poor
3 - Poor
4 - Not Good
5 - Average
6 - Normal
7 - Good
8 - Very Good
9 - Excellent
10 - Perfect

**Comment by JaneSjs** [comment]
+1 [request](https://surveyjs.answerdesk.io/internal/ticket/details/T12575): specify colors for rate items.

**Comment by novikov82** [comment]
All tasks are done, feature is released. Users requested the feature are informed.
Let's wait for feedback. Closing for now.
