### ISSUE TITLE
Ranking - selectToRank

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-library#5328]
### Info:
A Ranking question allows to order all its items. Introduce an option to order specific items. Similar to [the SortableJS third-party widget](https://surveyjs.io/form-library/examples/custom-widget-sortablejs/reactjs).

This functionality was asked in the following tickets:
* [T11460](https://surveyjs.answerdesk.io/internal/ticket/details/T11460)
* [T11156](https://surveyjs.answerdesk.io/internal/ticket/details/T11156)
* https://github.com/surveyjs/survey-library/issues/5160
* With a new functionality/question we will also handle PDF export ([T11710 - Pdf export issues: Exporting Custom Questions and Third-Party Widgets](https://surveyjs.answerdesk.io/internal/ticket/details/T11710)))

### Design @mikeamelin:
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=16490-295721&t=glnIb3Ck59k9YDhB-0
Two options — vertical + horizontal. 
Horizontal — default.
For mobile — vertical.

### Dev TODO:
- [x] functionality
- [ ] surveyjs/survey-pdf#249
- [x] surveyjs/survey-library#6346
- [ ] surveyjs/survey-library#6404

**Comment by JaneSjs** [comment]
With a new functionality/question we will also handle PDF export ([T11710 - Pdf export issues: Exporting Custom Questions and Third-Party Widgets](https://surveyjs.answerdesk.io/internal/ticket/details/T11710)))

**Comment by mikeamelin** [comment]
Design — https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=16171%3A291134&t=kL5yFGm88ST1tKem-4

Two options — vertical + horizontal. 
Horizontal — default.
For mobile — vertical.

**Comment by dmitrykurmanov** [comment]
@mikeamelin 
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=16490-295721
https://github.com/orgs/surveyjs/projects/13/views/1?pane=issue&itemId=23089107

**Comment by JaneSjs** [comment]
+1 https://github.com/surveyjs/survey-library/issues/5160

**Comment by dmitrykurmanov** [comment]
@RomanTsukanov  need to find a name for `selectToRankAlign` property proposal

**Comment by dmitrykurmanov** [comment]
Roman T. — Yesterday at 11:19 AM
selectToRankEnabled: true | false,
selectToRankAreasLayout: "horizontal" (рядом) | "vertical" (одна над другой)
selectToRankEmptyRankedAreaText: "All choices are ranked"
selectToRankEmptyUnrankedAreaText: "Drag and drop choices here to rank them"
